<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/tp-final-tchat-anonyme/assets/css/style.css">
    <script src="assets/javascript/script.js"></script>
    <title>Drocsid</title>
</head>
<body>
    <header>
        <div>
            <h1>Drocsid</h1>
            <img src="assets/images/logo.png" alt="Logo Drocsid">
        </div>
        <div>
            <a href="index.php?page=room">Chat</a>
            <a href="index.php?page=about">A propos</a>
        </div>
    </header>

    <main>
        <?php if (!isset($showSidebar) || $showSidebar !== false): ?>
            <aside class="rooms">
                <?php include "views/sidebar/sidebar_rooms.phtml" ?>
            </aside>
        <?php endif; ?>

        <section class="content">
            <?php include $view ?>
        </section>

        <div class="overlay">
            <?php include "views/room/createRoom.phtml"; ?>
        </div>

    </main>
</body>
</html>