<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/tp-final-tchat-anonyme/assets/css/style.css">
    <title>Tchat Anonyme</title>
</head>
<body>
    <header>
        <div>
            <h1>Tchat anonyme</h1>
            <img src="assets/images/logo.png" alt="Logo tchat anonyme">
        </div>
        <div>
            <a href="index.php?url=room">Chat</a>
            <a href="index.php?url=about">A propos</a>
        </div>
    </header>

    <main>
        <?php if (!isset($showSidebar) || $showSidebar !== false): ?>
            <aside class="rooms">
                <?php include "views/room/room.phtml" ?>
            </aside>
        <?php endif; ?>

        <section>
            <?php include $view ?>
        </section>

    </main>
</body>
</html>